[package]
name = "chimoney"
version = "0.0.0-unreleased"
edition = "2021"
description = "a wrapper for the Chimoney API"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
